#!/usr/bin/env bash
# This script configures HAProxy to distribute load among webserver 1 and webserver 2
sudo apt-get update
sudo apt-get install haproxy -y
sudo sed -i "\$aENABLED=1\n" /etc/default/haproxy
CUSTOMER_END="\\\nfrontend http_front\n\tbind *:80\n\tmode http\n\tdefault_backend http_back\n"
BACK_END="backend http_back\n\tbalance roundrobin\n\tserver 161099-web-01 54.144.85.84:80 check\n\tserver 161099-web-02 107.22.145.62:80 check\n"
sudo sed -i "\$a$CUSTOMER_END\n$BACK_END" /etc/haproxy/haproxy.cfg
sudo service haproxy restart
